version: '3.8'

services:

  vprodb:
    build:
      context: ./Docker-files/db
    image: tershoww/vprofiledb
    container_name: vprodb
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=salut123

  vproapp:
    build:
      context: ./Docker-files/app
    image: tershoww/vprofileapp
    container_name: vproapp
    ports:
      - "8080:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapps

  vproweb:
    build:
      context: ./Docker-files/web
    image: tershoww/vprofileweb
    container_name: vproweb
    ports:
      - "80:80"

  vprocache01:
    image: memcached
    ports:
      - "11211:11211"
  
  vpromq01:
    image: rabbitmq
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

volumes:
  vprodbdata: {}
  vproappdata: {} # That means create a volume in the docker engine itself